package com.microsoft.hack.buspasswallet.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.microsoft.hack.buspasswallet.database.User;
import com.microsoft.hack.buspasswallet.database.Pass;

import com.microsoft.hack.buspasswallet.database.UserDao;
import com.microsoft.hack.buspasswallet.database.PassDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig passDaoConfig;

    private final UserDao userDao;
    private final PassDao passDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        passDaoConfig = daoConfigMap.get(PassDao.class).clone();
        passDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        passDao = new PassDao(passDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(Pass.class, passDao);
    }
    
    public void clear() {
        userDaoConfig.getIdentityScope().clear();
        passDaoConfig.getIdentityScope().clear();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public PassDao getPassDao() {
        return passDao;
    }

}
